# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json


###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 87c20106082b034faf8cd28eb17fcdc2412a0e88

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/23/
Content-Type: application/json
Authorization: Token 87c20106082b034faf8cd28eb17fcdc2412a0e88

{
  "status": "OPEN"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json

###

# избранные объявления
GET {{baseUrl}}/advertisements/f/
Content-Type: application/json
Authorization: Token e7859ac478ebdd4ab77e2771b8d227c548aeb79b
